import {extras} from './extra-data';
export const languages=['English','हिन्दी','Français','Español','Deutsch','中文'];
const rows=[
['Gâteau Piment','starters',120,'6 pcs',1,1,0,'Split-pea fritters with fresh herbs and a chilli kick.','मसालेदार मटर के पकौड़े','Beignets de pois épicés','Buñuelos de guisantes','Würzige Erbsenbällchen','香辣豌豆丸'],
['Boulettes Dim Sum','starters',220,'6 pcs',0,0,0,'Steamed dumplings with a delicate savoury filling.','स्टीम्ड डिम सम','Boulettes vapeur','Dumplings al vapor','Gedämpfte Teigtaschen','清蒸点心'],
['Seafood Gratin','starters',340,'250g',0,0,0,'Tender seafood baked under a golden, creamy crust.','सीफूड ग्रैटिन','Gratin de fruits de mer','Gratinado de mariscos','Meeresfrüchte-Gratin','奶油焗海鲜'],
['Bol Renversé','mains',390,'450g',0,0,0,'Fragrant rice, chicken and vegetables crowned with an egg.','चिकन राइस बाउल','Bol renversé au poulet','Bol de arroz con pollo','Reisschale mit Hähnchen','鸡肉倒扣饭'],
['Cari Ourite','mains',490,'350g',0,0,0,'Slow-cooked octopus in a fragrant island curry.','ऑक्टोपस करी','Curry de poulpe','Curry de pulpo','Oktopus-Curry','章鱼咖喱'],
['Mauritian Chicken Biryani','mains',420,'550g',0,0,0,'Layers of spiced chicken and aromatic basmati rice.','मॉरीशस चिकन बिरयानी','Biryani de poulet mauricien','Biryani de pollo mauriciano','Mauritisches Hähnchen-Biryani','毛里求斯鸡肉香饭'],
['Poudine Maïs','desserts',150,'180g',1,0,1,'Soft cornmeal pudding with coconut and vanilla.','मकई पुडिंग','Pudding de maïs','Pudin de maíz','Maispudding','玉米布丁'],
['Bananes Flambées','desserts',230,'200g',1,0,1,'Caramelised bananas with a warm rum sauce.','फ्लैम्बे केले','Bananes flambées','Plátanos flambeados','Flambierte Bananen','火焰香蕉'],
['Napolitaine','desserts',100,'2 pcs',1,0,1,'Buttery shortbread with jam and delicate pink icing.','जैम बिस्कुट','Biscuits napolitains','Galletas con mermelada','Marmeladenkekse','果酱酥饼'],
['Alouda Milkshake','drinks',160,'300ml',1,0,1,'Chilled milk with basil seeds and a vanilla finish.','अलूदा मिल्कशेक','Milkshake alouda','Batido alouda','Alouda-Milchshake','阿卢达奶昔'],
['Bois Chéri Vanilla Tea','drinks',100,'250ml',1,1,1,'Locally grown black tea scented with soft vanilla.','वनीला चाय','Thé vanille de Bois Chéri','Té de vainilla','Bois-Chéri-Vanilletee','香草红茶'],
['Rhum Arrangé','drinks',280,'60ml',1,1,1,'Mauritian rum infused with tropical fruit and spices.','फलों वाला रम','Rhum arrangé','Ron infusionado','Aromatisierter Rum','水果香料朗姆酒']
];
const translatedDescriptions=[
['ताज़ी जड़ी-बूटियों और मिर्च के साथ मटर के पकौड़े।','स्वादिष्ट भरावन वाले भाप में पके डम्पलिंग।','सुनहरी मलाईदार परत में बेक किया गया सीफूड।','सुगंधित चावल, चिकन, सब्ज़ियाँ और अंडा।','द्वीप के मसालों में धीमी आँच पर पका ऑक्टोपस।','मसालेदार चिकन और सुगंधित बासमती चावल।','नारियल और वनीला के साथ नरम मकई पुडिंग।','गर्म रम सॉस के साथ कैरमेल केले।','जैम और गुलाबी आइसिंग वाले मक्खन बिस्कुट।','तुलसी के बीज और वनीला वाला ठंडा दूध।','वनीला की खुशबू वाली स्थानीय काली चाय।','उष्णकटिबंधीय फलों और मसालों वाला मॉरीशस रम।'],
['Beignets de pois aux herbes fraîches et au piment.','Boulettes vapeur à la farce délicatement savoureuse.','Fruits de mer sous une croûte dorée et crémeuse.','Riz parfumé, poulet et légumes, surmontés d’un œuf.','Poulpe mijoté dans un curry parfumé des îles.','Poulet épicé et riz basmati aromatique en couches.','Pudding de semoule de maïs à la noix de coco et vanille.','Bananes caramélisées, sauce chaude au rhum.','Sablés au beurre, confiture et glaçage rose.','Lait frais aux graines de basilic et à la vanille.','Thé noir local délicatement parfumé à la vanille.','Rhum mauricien infusé aux fruits tropicaux et épices.'],
['Buñuelos de guisantes con hierbas frescas y chile.','Dumplings al vapor con un delicado relleno salado.','Mariscos horneados bajo una costra dorada y cremosa.','Arroz aromático, pollo y verduras coronados con huevo.','Pulpo cocinado lentamente en curry de la isla.','Capas de pollo especiado y arroz basmati aromático.','Pudin suave de maíz con coco y vainilla.','Plátanos caramelizados con salsa caliente de ron.','Galletas de mantequilla con mermelada y glaseado rosa.','Leche fría con semillas de albahaca y vainilla.','Té negro local con un suave aroma de vainilla.','Ron mauriciano con frutas tropicales y especias.'],
['Erbsenbällchen mit frischen Kräutern und Chili.','Gedämpfte Teigtaschen mit herzhafter Füllung.','Zarte Meeresfrüchte unter einer goldenen Sahnekruste.','Duftender Reis, Hähnchen und Gemüse mit Ei.','Langsam gegarter Oktopus in aromatischem Inselcurry.','Würziges Hähnchen mit aromatischem Basmatireis.','Weicher Maispudding mit Kokos und Vanille.','Karamellisierte Bananen mit warmer Rumsauce.','Butterkekse mit Marmelade und rosa Glasur.','Kalte Milch mit Basilikumsamen und Vanille.','Lokaler Schwarztee mit sanfter Vanillenote.','Mauritischer Rum mit tropischen Früchten und Gewürzen.'],
['豌豆炸丸搭配新鲜香草与辣椒。','清蒸饺子，内馅鲜美细腻。','鲜嫩海鲜覆盖金黄奶油焗层。','香米搭配鸡肉、蔬菜和鸡蛋。','以海岛咖喱香料慢炖章鱼。','香料鸡肉与芳香印度香米层层相叠。','柔软玉米布丁，带有椰子与香草风味。','焦糖香蕉搭配温热朗姆酒酱。','黄油酥饼夹果酱，覆粉红糖霜。','冰牛奶搭配罗勒籽与香草。','本地红茶，散发柔和香草香气。','毛里求斯朗姆酒浸泡热带水果与香料。']
];
export const dishes=rows.map((r,i)=>({id:i,name:r[0],category:r[1],price:r[2],portion:r[3],veg:!!r[4],vegan:!!r[5],noAllium:!!r[6],names:[r[0],...r.slice(8)],descriptions:[r[7],...translatedDescriptions.map(d=>d[i])],model:(i===5?'Mauritian Chicken Biryani ':i===11?'Rhum Arrang':r[0])+'.glb'}));
export const categories=['starters','mains','desserts','drinks'];
const keys=['menu','close','search','filters','veg','nonveg','noAllium','filterTitle','low','high','vegan','diet','clear','apply','add','more','less','onTable','rotate','addOrder','allergens','allergenNote','itemsAdded','continue','order','request','itemsTotal','tax','total','waiter','waiterNote','empty','all','discover','subtitle','signature','starters','mains','desserts','drinks','preferences','sort','language','theme','quantity','arUnavailable','loading','modelError','sample','alcohol','photo','browse','yourOrder','remove','noMatches'];
const values=[
['Menu','Close','Search dishes','Filters','Veg','Non-veg','No onion / garlic','Filters & sorting','Price — low to high','Price — high to low','Vegan','Dietary restrictions','Clear all','Apply','ADD','Read more','Read less','View on table','Drag to rotate · Pinch to zoom','Add to order','Allergens','Ask your waiter about allergens before ordering.','items added','Continue','Your order','Add a cooking request (optional)','Items total','Tax (sample 15%)','Grand total','Show order to waiter','Please show this screen to your waiter. This order has not been sent.','Your order is empty','All dishes','A taste of the island.','Fresh flavours. Mauritian soul. Explore something delicious.','Island favourites','Starters','Main course','Desserts','Drinks','Preferences','Sort by','Language','Switch theme','Quantity','AR requires a supported phone and a secure connection. You can still explore in 3D.','Loading 3D model…','The model could not load. Please try again.','Sample menu · Prices, portions and dietary details need restaurant confirmation.','Contains alcohol','Dish photo','Browse menu','Made for your table','Remove','No dishes match these filters.'],
['मेनू','बंद करें','व्यंजन खोजें','फ़िल्टर','शाकाहारी','मांसाहारी','बिना प्याज़ / लहसुन','फ़िल्टर और क्रम','कीमत — कम से अधिक','कीमत — अधिक से कम','वीगन','आहार प्रतिबंध','सभी हटाएँ','लागू करें','जोड़ें','और पढ़ें','कम पढ़ें','मेज़ पर देखें','घुमाने के लिए खींचें · ज़ूम करें','ऑर्डर में जोड़ें','एलर्जी','ऑर्डर से पहले वेटर से एलर्जी की जानकारी लें।','आइटम जोड़े','आगे बढ़ें','आपका ऑर्डर','खाना बनाने का अनुरोध (वैकल्पिक)','आइटम कुल','कर (नमूना 15%)','कुल राशि','वेटर को ऑर्डर दिखाएँ','यह स्क्रीन वेटर को दिखाएँ। ऑर्डर भेजा नहीं गया है।','आपका ऑर्डर खाली है','सभी व्यंजन','द्वीप का स्वाद।','ताज़ा स्वाद। मॉरीशस की आत्मा। कुछ स्वादिष्ट खोजें।','द्वीप के पसंदीदा','स्टार्टर','मुख्य व्यंजन','मिठाइयाँ','पेय','पसंद','क्रम','भाषा','थीम बदलें','मात्रा','AR के लिए समर्थित फ़ोन और सुरक्षित कनेक्शन चाहिए। 3D देखें।','3D मॉडल लोड हो रहा है…','मॉडल लोड नहीं हुआ। फिर कोशिश करें।','नमूना मेनू · कीमत, मात्रा और आहार जानकारी की पुष्टि आवश्यक है।','अल्कोहल है','व्यंजन की तस्वीर','मेनू देखें','आपकी मेज़ के लिए','हटाएँ','कोई व्यंजन नहीं मिला।'],
['Menu','Fermer','Rechercher un plat','Filtres','Végétarien','Non végétarien','Sans oignon / ail','Filtres et tri','Prix croissant','Prix décroissant','Végétalien','Restrictions alimentaires','Tout effacer','Appliquer','AJOUTER','Lire plus','Lire moins','Voir sur la table','Glissez pour tourner · Pincez pour zoomer','Ajouter à la commande','Allergènes','Demandez conseil à votre serveur concernant les allergènes.','articles ajoutés','Continuer','Votre commande','Une demande en cuisine (facultatif)','Sous-total','Taxe (exemple 15 %)','Total','Montrer au serveur','Montrez cet écran au serveur. La commande n’a pas été envoyée.','Votre commande est vide','Tous les plats','Le goût de notre île.','Saveurs fraîches. Âme mauricienne. À vous de découvrir.','Les favoris de l’île','Entrées','Plats principaux','Desserts','Boissons','Préférences','Trier par','Langue','Changer le thème','Quantité','La RA nécessite un téléphone compatible et une connexion sécurisée. Explorez en 3D.','Chargement du modèle 3D…','Impossible de charger le modèle. Réessayez.','Menu exemple · Prix, portions et régimes à confirmer par le restaurant.','Contient de l’alcool','Photo du plat','Parcourir le menu','Pour votre table','Retirer','Aucun plat ne correspond aux filtres.'],
['Menú','Cerrar','Buscar platos','Filtros','Vegetariano','No vegetariano','Sin cebolla / ajo','Filtros y orden','Precio ascendente','Precio descendente','Vegano','Restricciones alimentarias','Borrar todo','Aplicar','AÑADIR','Leer más','Leer menos','Ver en la mesa','Arrastra para girar · Pellizca para ampliar','Añadir al pedido','Alérgenos','Consulta los alérgenos con tu camarero antes de pedir.','artículos añadidos','Continuar','Tu pedido','Petición a cocina (opcional)','Subtotal','Impuesto (ejemplo 15 %)','Total','Mostrar al camarero','Muestra esta pantalla al camarero. El pedido no se ha enviado.','Tu pedido está vacío','Todos los platos','El sabor de la isla.','Sabores frescos. Alma mauriciana. Descubre algo delicioso.','Favoritos de la isla','Entrantes','Platos principales','Postres','Bebidas','Preferencias','Ordenar','Idioma','Cambiar tema','Cantidad','La RA requiere un móvil compatible y conexión segura. Explora en 3D.','Cargando modelo 3D…','No se pudo cargar el modelo. Inténtalo de nuevo.','Menú de muestra · Confirmar precios, porciones y dietas con el restaurante.','Contiene alcohol','Foto del plato','Explorar menú','Para tu mesa','Eliminar','Ningún plato coincide con los filtros.'],
['Menü','Schließen','Gerichte suchen','Filter','Vegetarisch','Nicht vegetarisch','Ohne Zwiebel / Knoblauch','Filter und Sortierung','Preis aufsteigend','Preis absteigend','Vegan','Ernährung','Alles löschen','Anwenden','HINZUFÜGEN','Mehr lesen','Weniger lesen','Auf dem Tisch ansehen','Ziehen zum Drehen · Zum Zoomen spreizen','Zur Bestellung','Allergene','Fragen Sie vor der Bestellung nach Allergenen.','Artikel hinzugefügt','Weiter','Ihre Bestellung','Wunsch an die Küche (optional)','Zwischensumme','Steuer (Beispiel 15 %)','Gesamtbetrag','Dem Kellner zeigen','Zeigen Sie dies dem Kellner. Die Bestellung wurde nicht gesendet.','Ihre Bestellung ist leer','Alle Gerichte','Der Geschmack der Insel.','Frische Aromen. Mauritische Seele. Entdecken Sie Genuss.','Inselfavoriten','Vorspeisen','Hauptgerichte','Desserts','Getränke','Vorlieben','Sortieren','Sprache','Design wechseln','Menge','AR benötigt ein kompatibles Handy und eine sichere Verbindung. 3D bleibt verfügbar.','3D-Modell wird geladen…','Modell konnte nicht geladen werden. Bitte erneut versuchen.','Beispielmenü · Preise, Portionen und Ernährung vom Restaurant bestätigen lassen.','Enthält Alkohol','Gerichtfoto','Menü ansehen','Für Ihren Tisch','Entfernen','Keine passenden Gerichte.'],
['菜单','关闭','搜索菜品','筛选','素食','荤食','无洋葱 / 大蒜','筛选与排序','价格从低到高','价格从高到低','纯素','饮食限制','清除全部','应用','添加','展开','收起','放到桌面上','拖动旋转 · 双指缩放','加入订单','过敏原','点餐前请向服务员确认过敏原。','件已添加','继续','您的订单','添加烹饪要求（选填）','菜品小计','税费（示例15%）','合计','向服务员展示订单','请向服务员展示此页面。订单尚未发送。','订单为空','所有菜品','海岛的滋味。','新鲜风味，毛里求斯灵魂。发现美味。','海岛招牌','前菜','主菜','甜点','饮品','偏好','排序','语言','切换主题','数量','AR需要兼容手机和安全连接。您仍可查看3D。','正在加载3D模型…','模型加载失败，请重试。','示例菜单 · 价格、分量和饮食信息需餐厅确认。','含酒精','菜品照片','浏览菜单','为您的餐桌准备','移除','没有符合条件的菜品。']
];
export const translations=values.map(v=>Object.fromEntries(keys.map((k,i)=>[k,v[i]])));
export const asset=(name)=>'/assets/'+encodeURIComponent(name.replace(/\.png$/,'.webp'));

// Prototype pricing and the additional supplied single-photo dishes.
dishes.forEach((d,i)=>{d.price=[525,570,650,625,690,670,510,550,500,535,520,700][i]});
dishes.push(...extras);
categories.splice(2,0,'creole','pasta','breads','combos');
const categoryLabels=[['Creole soul','Fusion pasta','Breads & more','Combos'],['क्रियोल स्वाद','फ़्यूज़न पास्ता','ब्रेड और अधिक','कॉम्बो'],['Saveurs créoles','Pâtes fusion','Pains et plus','À partager'],['Sabor criollo','Pasta fusión','Panes y más','Combos'],['Kreolische Küche','Fusion-Pasta','Brot und mehr','Kombis'],['克里奥尔风味','融合意面','面包与更多','套餐']];
translations.forEach((t,i)=>{['creole','pasta','breads','combos'].forEach((k,j)=>t[k]=categoryLabels[i][j]);t.sample=['Client preview · Sample menu','क्लाइंट प्रीव्यू · नमूना मेनू','Aperçu client · Menu de démonstration','Vista previa · Menú de muestra','Kundenvorschau · Beispielmenü','客户预览 · 示例菜单'][i]});
