import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {dishes,categories,languages,translations,asset} from './data';
import './style.css';
const paths={search:'m21 21-5-5M19 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',close:'m6 6 12 12M6 18 18 6',globe:'M3 12h18M12 3a16 16 0 0 1 0 18 16 16 0 0 1 0-18M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',sun:'M12 3V1m0 22v-2M3 12H1m22 0h-2M5 5 3 3m18 18-2-2M5 19l-2 2M21 3l-2 2M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0',moon:'M21 14A9 9 0 0 1 10 3a9 9 0 1 0 11 11',cube:'m12 2 9 5v10l-9 5-9-5V7l9-5Zm0 10L3 7m9 5 9-5m-9 5v10M7.5 4.5l9 5',arrow:'M4 12h16m-6-6 6 6-6 6',chevron:'m6 9 6 6 6-6',filter:'M4 6h16M7 12h10M10 18h4',cutlery:'M4 2v6q0 3 3 3V22M7 2v9M10 2v6q0 3-3 3M19 2q-5 5-3 11h3m0-11v20',camera:'M4 7h4l2-3h4l2 3h4v14H4V7Zm12 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',bag:'M5 7h14l1 14H4L5 7Zm3 0V5a4 4 0 0 1 8 0v2',leaf:'M20 3Q1 1 4 16q14 8 16-13ZM4 21 15 10',minus:'M5 12h14',plus:'M5 12h14M12 5v14',check:'m5 12 4 4L19 6'};
function Icon({name}){return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.cutlery}/></svg>}
function App(){
const [lang,setLang]=useState(()=>Number(localStorage.getItem('lagon-lang'))||0),[dark,setDark]=useState(()=>localStorage.getItem('lagon-dark')==='true'),[splash,setSplash]=useState(!sessionStorage.getItem('lagon-entered'));
const [overlay,setOverlay]=useState(null),[cart,setCart]=useState({}),[filters,setFilters]=useState({prefs:[],allium:false,sort:''}),[draft,setDraft]=useState(filters),[query,setQuery]=useState(''),[quantity,setQuantity]=useState(1),[photo,setPhoto]=useState(0),[expanded,setExpanded]=useState({}),[active,setActive]=useState('all'),[request,setRequest]=useState(''),[arMessage,setArMessage]=useState('loading');
const t=translations[lang]||translations[0],viewer=useRef(),dialog=useRef(),carousel=useRef();
const money=n=>new Intl.NumberFormat(['en-MU','hi-IN','fr-MU','es-ES','de-DE','zh-CN'][lang],{style:'currency',currency:'MUR',maximumFractionDigits:0}).format(n);
const name=d=>d.names[lang]||d.name,desc=d=>d.descriptions[lang];
const open=(type,id)=>{if(type==='ar')import('@google/model-viewer').catch(()=>setArMessage('modelError'));history.pushState({lagon:{type,id}},'');setOverlay({type,id});setQuantity(1);setPhoto(0);setArMessage('loading')};
const close=()=>history.back();
useEffect(()=>{history.replaceState({lagon:null},'');const pop=e=>setOverlay(e.state?.lagon||null);addEventListener('popstate',pop);const timer=setTimeout(()=>{setSplash(false);sessionStorage.setItem('lagon-entered','1')},1900);return()=>{removeEventListener('popstate',pop);clearTimeout(timer)}},[]);
useEffect(()=>{localStorage.setItem('lagon-lang',lang);document.documentElement.lang=['en','hi','fr','es','de','zh'][lang]},[lang]);
useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.setItem('lagon-dark',dark)},[dark]);
useEffect(()=>{if(!overlay)return;const previous=document.activeElement;document.body.style.overflow='hidden';dialog.current?.focus();const key=e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const nodes=[...dialog.current.querySelectorAll('button,input,textarea,[tabindex="0"]')].filter(x=>!x.disabled);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};addEventListener('keydown',key);return()=>{document.body.style.overflow='';removeEventListener('keydown',key);previous?.focus()}},[overlay]);
useEffect(()=>{if(overlay?.type!=='ar'||!viewer.current)return;const v=viewer.current;const loaded=()=>setArMessage(''),failed=()=>setArMessage('modelError'),status=e=>{if(e.detail.status==='failed')setArMessage('arUnavailable')};v.addEventListener('load',loaded);v.addEventListener('error',failed);v.addEventListener('ar-status',status);return()=>{v.removeEventListener('load',loaded);v.removeEventListener('error',failed);v.removeEventListener('ar-status',status)}},[overlay]);
useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'read_menu',description:'Read the dishes available in the restaurant menu.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>dishes.map(d=>({id:d.id,name:d.name,price:d.price,currency:'MUR',category:d.category}))},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
const change=(id,delta)=>setCart(c=>({...c,[id]:Math.max(0,Math.min(99,(c[id]||0)+delta))}));
const matches=(d,f)=>!f.prefs.length||f.prefs.some(p=>p==='veg'?d.veg:p==='vegan'?d.vegan:!d.veg);
const filtered=f=>dishes.filter(d=>matches(d,f)&&(!f.allium||d.noAllium)).sort((a,b)=>f.sort==='low'?a.price-b.price:f.sort==='high'?b.price-a.price:a.id-b.id);
const visible=filtered(filters),count=Object.values(cart).reduce((a,b)=>a+b,0),subtotal=dishes.reduce((a,d)=>a+d.price*(cart[d.id]||0),0),total=Math.round(subtotal*1.15),selected=dishes.find(d=>d.id===overlay?.id);
const toggle=(f,key)=>({...f,prefs:f.prefs.includes(key)?f.prefs.filter(x=>x!==key):[...f.prefs,key]});
const goCategory=c=>{setActive(c);requestAnimationFrame(()=>document.getElementById(c==='all'?'dishes':c)?.scrollIntoView({behavior:'smooth',block:'start'}))};
const badge=d=><span className={'diet-badge '+(!d.veg?'non':'')} aria-label={d.veg?t.veg:t.nonveg}><svg viewBox="0 0 16 16" width="16" height="16"><rect x="1" y="1" width="14" height="14" rx="3" fill="none" stroke="currentColor"/>{d.veg?<circle cx="8" cy="8" r="3" fill="currentColor"/>:<path d="m8 4 4 7H4Z" fill="currentColor"/>}</svg></span>;
const stepper=(q,minus,plus,min=0)=><div className="stepper"><button aria-label={t.remove} onClick={minus} disabled={q<=min}><Icon name="minus"/></button><strong>{q}</strong><button aria-label={t.add} onClick={plus} disabled={q>=99}><Icon name="plus"/></button></div>;
const card=d=><article className="dish-card" key={d.id}><div className="dish-copy"><div className="tags">{badge(d)}<span>{d.vegan?t.vegan:d.veg?t.veg:t.nonveg}</span>{d.id===0&&<span className="pick">{t.signature}</span>}</div><h3>{name(d)} <span>({d.portion.replace('pcs',['pcs','पीस','pièces','uds.','Stk.','个'][lang])})</span></h3><strong className="price">{money(d.price)}</strong><p className={expanded[d.id]?'':'clamp'}>{desc(d)}</p><button className="text-button" onClick={()=>setExpanded({...expanded,[d.id]:!expanded[d.id]})}>{expanded[d.id]?t.less:t.more}</button></div><div className="dish-media"><button className="photo-button" onClick={()=>open('dish',d.id)} aria-label={name(d)+' — '+t.photo}><img src={asset(d.name+'.png')} alt={name(d)} loading="lazy"/></button>{d.model&&<button className="cube" aria-label={name(d)+' — 3D'} onClick={()=>open('ar',d.id)}><Icon name="cube"/></button>}{cart[d.id]?stepper(cart[d.id],()=>change(d.id,-1),()=>change(d.id,1)):<button className="add" onClick={()=>change(d.id,1)}>{t.add}<Icon name="plus"/></button>}</div></article>;
return <>{splash&&<div className="splash"><div><span className="brand">lagon<span>✳</span></span><p>ISLAND KITCHEN</p></div></div>}<header><div className="header-inner"><button className="icon-button" aria-label={t.search} onClick={()=>open('search')}><Icon name="search"/></button><a className="brand" href="#" onClick={e=>{e.preventDefault();window.scrollTo({top:0,behavior:'smooth'})}}>lagon<span>✳</span></a><div className="header-actions"><button className="icon-button language-button" aria-label={t.language} onClick={()=>open('language')}><Icon name="globe"/><span>{['EN','HI','FR','ES','DE','中文'][lang]}</span></button><button className="theme-toggle" aria-label={t.theme} onClick={()=>setDark(!dark)}><Icon name={dark?'moon':'sun'}/></button></div></div></header>
<main><section className="intro"><div><div className="eyebrow"><span/>LAGON · ISLAND KITCHEN</div><h1>{t.discover}</h1><p>{t.subtitle}</p></div><div className="ar-hint"><span className="ar-hint-icon"><Icon name="cube"/></span><div><strong>{t.onTable}</strong><span>{t.rotate}</span></div></div></section>
<nav className="category-tabs" aria-label={t.menu}>{['all',...categories].map(c=><button key={c} className={active===c?'active':''} onClick={()=>goCategory(c)}>{t[c]}{c==='all'&&<span>{dishes.length}</span>}</button>)}</nav>
<div className="filter-bar"><button onClick={()=>{setDraft({...filters,prefs:[...filters.prefs]});open('filters')}}><Icon name="filter"/>{t.filters}<Icon name="chevron"/></button><span className="divider"/>{['veg','nonveg'].map(k=><button key={k} className={filters.prefs.includes(k)?'selected':''} onClick={()=>setFilters(toggle(filters,k))}>{k==='veg'?<Icon name="leaf"/>:null}{t[k]}</button>)}<button className={filters.allium?'selected':''} onClick={()=>setFilters({...filters,allium:!filters.allium})}>{t.noAllium}</button></div>
<div id="dishes">{!visible.length&&<div className="empty"><h3>{t.noMatches}</h3><button className="primary" onClick={()=>setFilters({prefs:[],allium:false,sort:''})}>{t.clear}</button></div>}{categories.map(c=>{const list=visible.filter(d=>d.category===c);return !!list.length&&<section className="dish-section" id={c} key={c}><div className="section-title"><div><span className="section-number">{String(categories.indexOf(c)+1).padStart(2,'0')}</span><h2>{t[c]}</h2><span className="count">{list.length}</span></div><span className="section-line"/></div><div className="dish-grid">{list.map(card)}</div></section>})}</div><footer><span className="brand">lagon<span>✳</span></span><p>{t.sample}</p></footer></main>
{(!overlay||overlay.type==='menu')&&<button className={'menu-fab '+(overlay?.type==='menu'?'opened':'')+' '+(count?'with-cart':'')} onClick={()=>overlay?.type==='menu'?close():open('menu')}><Icon name={overlay?.type==='menu'?'close':'cutlery'}/>{overlay?.type==='menu'?t.close:t.menu}</button>}
{count>0&&!overlay&&<div className="cart-bar"><div className="cart-bar-inner"><span className="cart-icon"><Icon name="bag"/><b>{count}</b></span><div><strong>{count} {t.itemsAdded}</strong><span>{money(subtotal)}</span></div><button onClick={()=>open('cart')}>{t.continue}<Icon name="arrow"/></button></div></div>}
{overlay&&<div className={'backdrop '+(overlay.type==='menu'?'menu-backdrop':'')} onClick={e=>{if(e.target===e.currentTarget)close()}}><section ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-label={selected?name(selected):t[overlay.type]||t.menu} className={'modal '+overlay.type}><button className="modal-close icon-button" aria-label={t.close} onClick={close}><Icon name="close"/></button>
{overlay.type==='language'&&<><h2>{t.language}</h2><div className="language-list">{languages.map((l,i)=><button key={l} className={lang===i?'selected':''} onClick={()=>{setLang(i);close()}}>{l}{lang===i&&<Icon name="check"/>}</button>)}</div></>}
{overlay.type==='search'&&<><h2>{t.search}</h2><label className="search-input"><Icon name="search"/><input autoFocus placeholder={t.search} value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="gallery">{dishes.filter(d=>(name(d)+' '+desc(d)).toLowerCase().includes(query.toLowerCase())).map(d=><button key={d.id} onClick={()=>open('dish',d.id)}><img src={asset(d.name+'.png')} alt={name(d)} loading="lazy"/><span>{name(d)}<small>{money(d.price)}</small></span></button>)}</div>{!dishes.some(d=>(name(d)+' '+desc(d)).toLowerCase().includes(query.toLowerCase()))&&<p>{t.noMatches}</p>}</>}
{overlay.type==='filters'&&<><div className="handle"/><h2>{t.filterTitle}</h2><h3>{t.sort}</h3><div className="filter-options">{['low','high'].map(k=><button className={draft.sort===k?'selected':''} onClick={()=>setDraft({...draft,sort:draft.sort===k?'':k})} key={k}>{t[k]}{draft.sort===k&&<Icon name="check"/>}</button>)}</div><h3>{t.preferences}</h3><div className="filter-options">{['veg','nonveg','vegan'].map(k=><button key={k} className={draft.prefs.includes(k)?'selected':''} onClick={()=>setDraft(toggle(draft,k))}>{t[k]}{draft.prefs.includes(k)&&<Icon name="check"/>}</button>)}</div><h3>{t.diet}</h3><button className={'restriction '+(draft.allium?'selected':'')} onClick={()=>setDraft({...draft,allium:!draft.allium})}>{t.noAllium}<span className="checkbox">{draft.allium&&<Icon name="check"/>}</span></button><div className="sheet-actions"><button className="clear" onClick={()=>setDraft({prefs:[],allium:false,sort:''})}>{t.clear}</button><button className="primary" onClick={()=>{setFilters(draft);close()}}>{t.apply} ({filtered(draft).length})</button></div></>}
{overlay.type==='dish'&&selected&&<><div className="carousel" ref={carousel} onScroll={e=>setPhoto(Math.round(e.currentTarget.scrollLeft/e.currentTarget.clientWidth))}>{(selected.model?['',' 2',' 3']:['']).map(s=><img key={s} src={asset(selected.name+s+'.png')} alt={name(selected)+' '+(s||'1')}/>)}</div>{selected.model&&<div className="dots">{[0,1,2].map(i=><button key={i} aria-label={t.photo+' '+(i+1)} className={photo===i?'active':''} onClick={()=>carousel.current.scrollTo({left:carousel.current.clientWidth*i,behavior:'smooth'})}/>)}</div>}<div className="detail-content"><div className="tags">{badge(selected)}{selected.veg?t.veg:t.nonveg}</div><h2>{name(selected)}</h2><strong className="price">{money(selected.price)}</strong><p>{desc(selected)}</p><div className="allergens"><strong>{t.allergens}</strong><p>{t.allergenNote}</p>{[7,11].includes(selected.id)&&<p>{t.alcohol}</p>}</div><div className="quantity-row"><span>{t.quantity}</span>{stepper(quantity,()=>setQuantity(Math.max(1,quantity-1)),()=>setQuantity(quantity+1),1)}</div><button className="primary full" onClick={()=>{change(selected.id,quantity);close()}}>{t.addOrder} · {money(selected.price*quantity)}</button></div></>}
{overlay.type==='ar'&&selected&&<><div className="ar-heading"><div className="eyebrow">LAGON · 3D</div><h2>{name(selected)}</h2></div><model-viewer ref={viewer} src={asset(selected.model)} poster={asset(selected.name+'.png')} alt={name(selected)} camera-controls auto-rotate ar ar-modes="webxr scene-viewer quick-look" ar-scale="fixed" shadow-intensity="1" exposure="1" touch-action="pan-y"><button slot="ar-button" style={{display:'none'}}/></model-viewer><div className="ar-bottom"><p role="status">{arMessage?t[arMessage]:t.rotate}</p><button className="primary" disabled={arMessage==='loading'||arMessage==='modelError'} onClick={async()=>{if(viewer.current?.canActivateAR){try{await viewer.current.activateAR()}catch{setArMessage('arUnavailable')}}else setArMessage('arUnavailable')}}><Icon name="camera"/>{t.onTable}</button></div></>}
{overlay.type==='menu'&&<><div className="eyebrow">LAGON · ISLAND KITCHEN</div><h2>{t.browse}</h2>{categories.map(c=><div className="drawer-category" key={c}><div><button onClick={()=>{close();setTimeout(()=>goCategory(c),100)}}>{t[c]}<span>{dishes.filter(d=>d.category===c).length}</span></button><button aria-label={t[c]} onClick={()=>setExpanded({...expanded,[c]:!expanded[c]})}><Icon name="chevron"/></button></div>{expanded[c]&&['veg','nonveg'].map(k=>{const n=dishes.filter(d=>d.category===c&&(k==='veg'?d.veg:!d.veg)).length;return n>0&&<button className="subcategory" key={k} onClick={()=>{setFilters({...filters,prefs:[k]});close();setTimeout(()=>goCategory(c),100)}}>{t[k]}<span>{n}</span></button>})}</div>)}</>}
{['cart','waiter'].includes(overlay.type)&&<><div className="eyebrow">LAGON · ISLAND KITCHEN</div><h2>{overlay.type==='waiter'?t.yourOrder:t.order}</h2>{overlay.type==='waiter'&&<div className="waiter-note"><Icon name="check"/><p>{t.waiterNote}</p></div>}{!count?<div className="empty"><Icon name="bag"/><p>{t.empty}</p></div>:<><div className="order-list">{dishes.filter(d=>cart[d.id]).map(d=><div className="order-item" key={d.id}><img src={asset(d.name+'.png')} alt=""/><div><h3>{name(d)}</h3>{overlay.type==='cart'?stepper(cart[d.id],()=>change(d.id,-1),()=>change(d.id,1)):<span>× {cart[d.id]}</span>}</div><strong>{money(d.price*cart[d.id])}</strong></div>)}</div>{overlay.type==='cart'?<label className="request-label">{t.request}<textarea value={request} maxLength={500} onChange={e=>setRequest(e.target.value)}/></label>:request&&<p className="request-summary">{request}</p>}<div className="bill"><div><span>{t.itemsTotal}</span><span>{money(subtotal)}</span></div><div><span>{t.tax}</span><span>{money(total-subtotal)}</span></div><div className="grand"><strong>{t.total}</strong><strong>{money(total)}</strong></div></div>{overlay.type==='cart'&&<button className="primary full" onClick={()=>open('waiter')}>{t.waiter}<Icon name="arrow"/></button>}<p className="sample-note">{t.sample}</p></>}</>}
</section></div>}
</>}
createRoot(document.getElementById('root')).render(<App/>);
